%% generated by soap from: /home/rcarauta/desenvolvimento/erlang/soap/ebin/correios.wsdl
%% for service "AtendeClienteService" and port "AtendeClientePort"
%% using options: [{service,"AtendeClienteService"},{port,"AtendeClientePort"},{generate,both},{namespaces,[{"http://cliente.bean.master.sigep.bsb.correios.com.br/","P0"}]},{generate_tests,none},{http_server,soap_server_cowboy_2},{server_name,"correios_server"},{http_client,soap_client_ibrowse},{client_name,"correios_client"},{strict,true}]

-module(correios_server).

-include("correios.hrl").

-export([buscaServicosAdicionaisAtivos/3]).
-export([fechaPlp/3]).
-export([consultaSRO/3]).
-export([calculaTarifaServico/3]).
-export([validaPlp/3]).
-export(['VerificaSeTodosObjetosCancelados'/3]).
-export([cancelarObjeto/3]).
-export([atualizaPagamentoNaEntrega/3]).
-export([obterClienteAtualizacao/3]).
-export([verificaDisponibilidadeServico/3]).
-export([fechaPlpVariosServicos/3]).
-export([geraDigitoVerificadorEtiquetas/3]).
-export([obterEmbalagemLRS/3]).
-export([validaEtiquetaPLP/3]).
-export([buscaServicosValorDeclarado/3]).
-export([consultaCEP/3]).
-export([integrarUsuarioScol/3]).
-export([atualizaRemessaAgrupada/3]).
-export([solicitaPLP/3]).
-export([getStatusCartaoPostagem/3]).
-export([buscaTarifaVale/3]).
-export([validarPostagemSimultanea/3]).
-export([getStatusPLP/3]).
-export([buscaServicosXServicosAdicionais/3]).
-export([cancelarPedidoScol/3]).
-export([bloquearObjeto/3]).
-export([buscaContrato/3]).
-export([solicitaEtiquetas/3]).
-export([solicitaXmlPlp/3]).
-export([validarPostagemReversa/3]).
-export([buscaCliente/3]).
-export([buscaPagamentoEntrega/3]).
-export([solicitarPostagemScol/3]).
-export([buscaServicos/3]).
-export([interface/0]).

-spec buscaServicosAdicionaisAtivos(Parsed_body::'P0:buscaServicosAdicionaisAtivos'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:buscaServicosAdicionaisAtivosResponse'()).
buscaServicosAdicionaisAtivos(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:buscaServicosAdicionaisAtivosResponse'{}, Soap_req, State}.

-spec fechaPlp(Parsed_body::'P0:fechaPlp'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:fechaPlpResponse'()).
fechaPlp(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:fechaPlpResponse'{}, Soap_req, State}.

-spec consultaSRO(Parsed_body::'P0:consultaSRO'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:consultaSROResponse'()).
consultaSRO(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:consultaSROResponse'{}, Soap_req, State}.

-spec calculaTarifaServico(Parsed_body::'P0:calculaTarifaServico'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:calculaTarifaServicoResponse'()).
calculaTarifaServico(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:calculaTarifaServicoResponse'{}, Soap_req, State}.

-spec validaPlp(Parsed_body::'P0:validaPlp'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:validaPlpResponse'()).
validaPlp(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:validaPlpResponse'{}, Soap_req, State}.

-spec 'VerificaSeTodosObjetosCancelados'(Parsed_body::'P0:VerificaSeTodosObjetosCancelados'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:VerificaSeTodosObjetosCanceladosResponse'()).
'VerificaSeTodosObjetosCancelados'(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:VerificaSeTodosObjetosCanceladosResponse'{}, Soap_req, State}.

-spec cancelarObjeto(Parsed_body::'P0:cancelarObjeto'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:cancelarObjetoResponse'()).
cancelarObjeto(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:cancelarObjetoResponse'{}, Soap_req, State}.

-spec atualizaPagamentoNaEntrega(Parsed_body::'P0:atualizaPagamentoNaEntrega'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:atualizaPagamentoNaEntregaResponse'()).
atualizaPagamentoNaEntrega(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:atualizaPagamentoNaEntregaResponse'{}, Soap_req, State}.

-spec obterClienteAtualizacao(Parsed_body::'P0:obterClienteAtualizacao'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:obterClienteAtualizacaoResponse'()).
obterClienteAtualizacao(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:obterClienteAtualizacaoResponse'{}, Soap_req, State}.

-spec verificaDisponibilidadeServico(Parsed_body::'P0:verificaDisponibilidadeServico'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:verificaDisponibilidadeServicoResponse'()).
verificaDisponibilidadeServico(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:verificaDisponibilidadeServicoResponse'{}, Soap_req, State}.

-spec fechaPlpVariosServicos(Parsed_body::'P0:fechaPlpVariosServicos'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:fechaPlpVariosServicosResponse'()).
fechaPlpVariosServicos(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:fechaPlpVariosServicosResponse'{}, Soap_req, State}.

-spec geraDigitoVerificadorEtiquetas(Parsed_body::'P0:geraDigitoVerificadorEtiquetas'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:geraDigitoVerificadorEtiquetasResponse'()).
geraDigitoVerificadorEtiquetas(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:geraDigitoVerificadorEtiquetasResponse'{}, Soap_req, State}.

-spec obterEmbalagemLRS(Parsed_body::'P0:obterEmbalagemLRS'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:obterEmbalagemLRSResponse'()).
obterEmbalagemLRS(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:obterEmbalagemLRSResponse'{}, Soap_req, State}.

-spec validaEtiquetaPLP(Parsed_body::'P0:validaEtiquetaPLP'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:validaEtiquetaPLPResponse'()).
validaEtiquetaPLP(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:validaEtiquetaPLPResponse'{}, Soap_req, State}.

-spec buscaServicosValorDeclarado(Parsed_body::'P0:buscaServicosValorDeclarado'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:buscaServicosValorDeclaradoResponse'()).
buscaServicosValorDeclarado(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:buscaServicosValorDeclaradoResponse'{}, Soap_req, State}.

-spec consultaCEP(Parsed_body::'P0:consultaCEP'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:consultaCEPResponse'()).
consultaCEP(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:consultaCEPResponse'{}, Soap_req, State}.

-spec integrarUsuarioScol(Parsed_body::'P0:integrarUsuarioScol'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:integrarUsuarioScolResponse'()).
integrarUsuarioScol(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:integrarUsuarioScolResponse'{}, Soap_req, State}.

-spec atualizaRemessaAgrupada(Parsed_body::'P0:atualizaRemessaAgrupada'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:atualizaRemessaAgrupadaResponse'()).
atualizaRemessaAgrupada(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:atualizaRemessaAgrupadaResponse'{}, Soap_req, State}.

-spec solicitaPLP(Parsed_body::'P0:solicitaPLP'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:solicitaPLPResponse'()).
solicitaPLP(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:solicitaPLPResponse'{}, Soap_req, State}.

-spec getStatusCartaoPostagem(Parsed_body::'P0:getStatusCartaoPostagem'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:getStatusCartaoPostagemResponse'()).
getStatusCartaoPostagem(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:getStatusCartaoPostagemResponse'{}, Soap_req, State}.

-spec buscaTarifaVale(Parsed_body::'P0:buscaTarifaVale'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:buscaTarifaValeResponse'()).
buscaTarifaVale(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:buscaTarifaValeResponse'{}, Soap_req, State}.

-spec validarPostagemSimultanea(Parsed_body::'P0:validarPostagemSimultanea'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:validarPostagemSimultaneaResponse'()).
validarPostagemSimultanea(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:validarPostagemSimultaneaResponse'{}, Soap_req, State}.

-spec getStatusPLP(Parsed_body::'P0:getStatusPLP'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:getStatusPLPResponse'()).
getStatusPLP(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:getStatusPLPResponse'{}, Soap_req, State}.

-spec buscaServicosXServicosAdicionais(Parsed_body::'P0:buscaServicosXServicosAdicionais'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:buscaServicosXServicosAdicionaisResponse'()).
buscaServicosXServicosAdicionais(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:buscaServicosXServicosAdicionaisResponse'{}, Soap_req, State}.

-spec cancelarPedidoScol(Parsed_body::'P0:cancelarPedidoScol'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:cancelarPedidoScolResponse'()).
cancelarPedidoScol(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:cancelarPedidoScolResponse'{}, Soap_req, State}.

-spec bloquearObjeto(Parsed_body::'P0:bloquearObjeto'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:bloquearObjetoResponse'()).
bloquearObjeto(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:bloquearObjetoResponse'{}, Soap_req, State}.

-spec buscaContrato(Parsed_body::'P0:buscaContrato'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:buscaContratoResponse'()).
buscaContrato(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:buscaContratoResponse'{}, Soap_req, State}.

-spec solicitaEtiquetas(Parsed_body::'P0:solicitaEtiquetas'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:solicitaEtiquetasResponse'()).
solicitaEtiquetas(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:solicitaEtiquetasResponse'{}, Soap_req, State}.

-spec solicitaXmlPlp(Parsed_body::'P0:solicitaXmlPlp'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:solicitaXmlPlpResponse'()).
solicitaXmlPlp(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:solicitaXmlPlpResponse'{}, Soap_req, State}.

-spec validarPostagemReversa(Parsed_body::'P0:validarPostagemReversa'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:validarPostagemReversaResponse'()).
validarPostagemReversa(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:validarPostagemReversaResponse'{}, Soap_req, State}.

-spec buscaCliente(Parsed_body::'P0:buscaCliente'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:buscaClienteResponse'()).
buscaCliente(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:buscaClienteResponse'{}, Soap_req, State}.

-spec buscaPagamentoEntrega(Parsed_body::'P0:buscaPagamentoEntrega'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:buscaPagamentoEntregaResponse'()).
buscaPagamentoEntrega(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:buscaPagamentoEntregaResponse'{}, Soap_req, State}.

-spec solicitarPostagemScol(Parsed_body::'P0:solicitarPostagemScol'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:solicitarPostagemScolResponse'()).
solicitarPostagemScol(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:solicitarPostagemScolResponse'{}, Soap_req, State}.

-spec buscaServicos(Parsed_body::'P0:buscaServicos'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:buscaServicosResponse'()).
buscaServicos(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:buscaServicosResponse'{}, Soap_req, State}.

%% The 'interface()' function is used by the SOAP framework to access information about
%% the WSDL.
interface() ->
    ?INTERFACE.
