%% generated by soap from: /home/rcarauta/desenvolvimento/erlang/soap/ebin/correios.wsdl
%% for service "AtendeClienteService" and port "AtendeClientePort"
%% using options: [{service,"AtendeClienteService"},{port,"AtendeClientePort"},{generate,both},{namespaces,[{"http://cliente.bean.master.sigep.bsb.correios.com.br/","P0"}]},{generate_tests,none},{http_server,soap_server_cowboy_2},{server_name,"correios_server"},{http_client,soap_client_ibrowse},{client_name,"correios_client"},{strict,true}]

-module(correios_client).

-include("correios.hrl").

-export([interface/0]).

%% The functions that are described by the WSDL
-export([buscaServicosAdicionaisAtivos/3]).
-export([fechaPlp/3]).
-export([consultaSRO/3]).
-export([calculaTarifaServico/3]).
-export([validaPlp/3]).
-export(['VerificaSeTodosObjetosCancelados'/3]).
-export([cancelarObjeto/3]).
-export([atualizaPagamentoNaEntrega/3]).
-export([obterClienteAtualizacao/3]).
-export([verificaDisponibilidadeServico/3]).
-export([fechaPlpVariosServicos/3]).
-export([geraDigitoVerificadorEtiquetas/3]).
-export([obterEmbalagemLRS/3]).
-export([validaEtiquetaPLP/3]).
-export([buscaServicosValorDeclarado/3]).
-export([consultaCEP/3]).
-export([integrarUsuarioScol/3]).
-export([atualizaRemessaAgrupada/3]).
-export([solicitaPLP/3]).
-export([getStatusCartaoPostagem/3]).
-export([buscaTarifaVale/3]).
-export([validarPostagemSimultanea/3]).
-export([getStatusPLP/3]).
-export([buscaServicosXServicosAdicionais/3]).
-export([cancelarPedidoScol/3]).
-export([bloquearObjeto/3]).
-export([buscaContrato/3]).
-export([solicitaEtiquetas/3]).
-export([solicitaXmlPlp/3]).
-export([validarPostagemReversa/3]).
-export([buscaCliente/3]).
-export([buscaPagamentoEntrega/3]).
-export([solicitarPostagemScol/3]).
-export([buscaServicos/3]).

-spec buscaServicosAdicionaisAtivos(Soap_body::'P0:buscaServicosAdicionaisAtivos'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:buscaServicosAdicionaisAtivosResponse'()).
buscaServicosAdicionaisAtivos(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec fechaPlp(Soap_body::'P0:fechaPlp'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:fechaPlpResponse'()).
fechaPlp(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec consultaSRO(Soap_body::'P0:consultaSRO'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:consultaSROResponse'()).
consultaSRO(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec calculaTarifaServico(Soap_body::'P0:calculaTarifaServico'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:calculaTarifaServicoResponse'()).
calculaTarifaServico(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec validaPlp(Soap_body::'P0:validaPlp'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:validaPlpResponse'()).
validaPlp(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec 'VerificaSeTodosObjetosCancelados'(Soap_body::'P0:VerificaSeTodosObjetosCancelados'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:VerificaSeTodosObjetosCanceladosResponse'()).
'VerificaSeTodosObjetosCancelados'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec cancelarObjeto(Soap_body::'P0:cancelarObjeto'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:cancelarObjetoResponse'()).
cancelarObjeto(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec atualizaPagamentoNaEntrega(Soap_body::'P0:atualizaPagamentoNaEntrega'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:atualizaPagamentoNaEntregaResponse'()).
atualizaPagamentoNaEntrega(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec obterClienteAtualizacao(Soap_body::'P0:obterClienteAtualizacao'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:obterClienteAtualizacaoResponse'()).
obterClienteAtualizacao(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec verificaDisponibilidadeServico(Soap_body::'P0:verificaDisponibilidadeServico'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:verificaDisponibilidadeServicoResponse'()).
verificaDisponibilidadeServico(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec fechaPlpVariosServicos(Soap_body::'P0:fechaPlpVariosServicos'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:fechaPlpVariosServicosResponse'()).
fechaPlpVariosServicos(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec geraDigitoVerificadorEtiquetas(Soap_body::'P0:geraDigitoVerificadorEtiquetas'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:geraDigitoVerificadorEtiquetasResponse'()).
geraDigitoVerificadorEtiquetas(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec obterEmbalagemLRS(Soap_body::'P0:obterEmbalagemLRS'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:obterEmbalagemLRSResponse'()).
obterEmbalagemLRS(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec validaEtiquetaPLP(Soap_body::'P0:validaEtiquetaPLP'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:validaEtiquetaPLPResponse'()).
validaEtiquetaPLP(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec buscaServicosValorDeclarado(Soap_body::'P0:buscaServicosValorDeclarado'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:buscaServicosValorDeclaradoResponse'()).
buscaServicosValorDeclarado(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec consultaCEP(Soap_body::'P0:consultaCEP'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:consultaCEPResponse'()).
consultaCEP(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec integrarUsuarioScol(Soap_body::'P0:integrarUsuarioScol'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:integrarUsuarioScolResponse'()).
integrarUsuarioScol(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec atualizaRemessaAgrupada(Soap_body::'P0:atualizaRemessaAgrupada'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:atualizaRemessaAgrupadaResponse'()).
atualizaRemessaAgrupada(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec solicitaPLP(Soap_body::'P0:solicitaPLP'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:solicitaPLPResponse'()).
solicitaPLP(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec getStatusCartaoPostagem(Soap_body::'P0:getStatusCartaoPostagem'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:getStatusCartaoPostagemResponse'()).
getStatusCartaoPostagem(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec buscaTarifaVale(Soap_body::'P0:buscaTarifaVale'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:buscaTarifaValeResponse'()).
buscaTarifaVale(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec validarPostagemSimultanea(Soap_body::'P0:validarPostagemSimultanea'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:validarPostagemSimultaneaResponse'()).
validarPostagemSimultanea(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec getStatusPLP(Soap_body::'P0:getStatusPLP'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:getStatusPLPResponse'()).
getStatusPLP(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec buscaServicosXServicosAdicionais(Soap_body::'P0:buscaServicosXServicosAdicionais'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:buscaServicosXServicosAdicionaisResponse'()).
buscaServicosXServicosAdicionais(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec cancelarPedidoScol(Soap_body::'P0:cancelarPedidoScol'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:cancelarPedidoScolResponse'()).
cancelarPedidoScol(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec bloquearObjeto(Soap_body::'P0:bloquearObjeto'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:bloquearObjetoResponse'()).
bloquearObjeto(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec buscaContrato(Soap_body::'P0:buscaContrato'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:buscaContratoResponse'()).
buscaContrato(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec solicitaEtiquetas(Soap_body::'P0:solicitaEtiquetas'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:solicitaEtiquetasResponse'()).
solicitaEtiquetas(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec solicitaXmlPlp(Soap_body::'P0:solicitaXmlPlp'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:solicitaXmlPlpResponse'()).
solicitaXmlPlp(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec validarPostagemReversa(Soap_body::'P0:validarPostagemReversa'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:validarPostagemReversaResponse'()).
validarPostagemReversa(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec buscaCliente(Soap_body::'P0:buscaCliente'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:buscaClienteResponse'()).
buscaCliente(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec buscaPagamentoEntrega(Soap_body::'P0:buscaPagamentoEntrega'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:buscaPagamentoEntregaResponse'()).
buscaPagamentoEntrega(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec solicitarPostagemScol(Soap_body::'P0:solicitarPostagemScol'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:solicitarPostagemScolResponse'()).
solicitarPostagemScol(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec buscaServicos(Soap_body::'P0:buscaServicos'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:buscaServicosResponse'()).
buscaServicos(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

%%% --------------------------------------------------------------------
%%% Internal functions
%%% --------------------------------------------------------------------
interface() ->
    ?INTERFACE.