%% generated by soap from: /home/rcarauta/desenvolvimento/erlang/soap/ebin/tempconvert.wsdl
%% for service "TempConvert" and port "TempConvertSoap12"
%% using options: [{service,"TempConvert"},{port,"TempConvertSoap12"},{generate,both},{namespaces,[{"https://www.w3schools.com/xml/","P0"}]},{generate_tests,none},{http_server,soap_server_cowboy_2},{server_name,"tempconvert_server"},{http_client,soap_client_ibrowse},{client_name,"tempconvert_client"},{strict,true}]

-module(tempconvert_client).

-include("tempconvert.hrl").

-export([interface/0]).

%% The functions that are described by the WSDL
-export(['FahrenheitToCelsius'/3]).
-export(['CelsiusToFahrenheit'/3]).

-spec 'FahrenheitToCelsius'(Soap_body::'P0:FahrenheitToCelsius'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:FahrenheitToCelsiusResponse'()).
'FahrenheitToCelsius'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

-spec 'CelsiusToFahrenheit'(Soap_body::'P0:CelsiusToFahrenheit'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:CelsiusToFahrenheitResponse'()).
'CelsiusToFahrenheit'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"\"", interface()).

%%% --------------------------------------------------------------------
%%% Internal functions
%%% --------------------------------------------------------------------
interface() ->
    ?INTERFACE.