%% generated by soap from: /home/rcarauta/desenvolvimento/erlang/soap/ebin/tempconvert.wsdl
%% for service "TempConvert" and port "TempConvertSoap12"
%% using options: [{service,"TempConvert"},{port,"TempConvertSoap12"},{generate,both},{namespaces,[{"https://www.w3schools.com/xml/","P0"}]},{generate_tests,none},{http_server,soap_server_cowboy_2},{server_name,"tempconvert_server"},{http_client,soap_client_ibrowse},{client_name,"tempconvert_client"},{strict,true}]

-module(tempconvert_server).

-include("tempconvert.hrl").

-export(['FahrenheitToCelsius'/3]).
-export(['CelsiusToFahrenheit'/3]).
-export([interface/0]).

-spec 'FahrenheitToCelsius'(Parsed_body::'P0:FahrenheitToCelsius'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:FahrenheitToCelsiusResponse'()).
'FahrenheitToCelsius'(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:FahrenheitToCelsiusResponse'{}, Soap_req, State}.

-spec 'CelsiusToFahrenheit'(Parsed_body::'P0:CelsiusToFahrenheit'(),
    Soap_req::soap:soap_req(), State::soap:soap_handler_state())
    -> soap:soap_handler_response('P0:CelsiusToFahrenheitResponse'()).
'CelsiusToFahrenheit'(_Parsed_body, Soap_req, State) ->
    %% your implementation goes here
    {ok, #'P0:CelsiusToFahrenheitResponse'{}, Soap_req, State}.

%% The 'interface()' function is used by the SOAP framework to access information about
%% the WSDL.
interface() ->
    ?INTERFACE.
